# Generated by Django 3.1.7 on 2021-03-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='User',
            new_name='user',
        ),
    ]
